// Canonical module keys — must match the `module_name` values seeded in
// supabase/migrations/0004_user_management_and_rls.sql exactly.
export const MODULE_LIST = [
    { key: 'residents', label: 'Resident Registration' },
    { key: 'households', label: 'Household Management' },
    { key: 'puroks', label: 'Purok Management' },
    { key: 'families', label: 'Family Profiling' },
    { key: 'seniorCitizens', label: 'Senior Citizens' },
    { key: 'pwdRecords', label: 'PWD' },
    { key: 'soloParents', label: 'Solo Parents' },
    { key: 'voters', label: 'Voters Information' },
    { key: 'youthProfiles', label: 'Youth (SK)' },
    { key: 'residentSearch', label: 'Resident Search' },
    { key: 'certificates', label: 'Certificates' },
    { key: 'blotter', label: 'Blotter Records' },
    { key: 'businesses', label: 'Business Registration' },
    { key: 'businessClearance', label: 'Business Clearance' },
    { key: 'permitRenewal', label: 'Permit Renewal' },
    { key: 'businessOwners', label: 'Business Owners' },
    { key: 'businessReports', label: 'Business Reports' },
    { key: 'collections', label: 'Collection' },
    { key: 'receipts', label: 'Official Receipts' },
    { key: 'expenses', label: 'Expenses' },
    { key: 'budget', label: 'Budget' },
    { key: 'financialReports', label: 'Financial Reports' },
    { key: 'auditTrail', label: 'Audit Trail' },
    { key: 'healthRecords', label: 'Health Records' },
    { key: 'vaccinations', label: 'Vaccination' },
    { key: 'prenatalCare', label: 'Prenatal Care' },
    { key: 'medicalAssistance', label: 'Medical Assistance' },
    { key: 'medicineInventory', label: 'Medicine Inventory' },
    { key: 'evacuationCenters', label: 'Evacuation Centers' },
    { key: 'disasterIncidents', label: 'Disaster Incidents' },
    { key: 'reliefDistribution', label: 'Relief Distribution' },
    { key: 'rescueOperations', label: 'Rescue Operations' },
    { key: 'disasterReports', label: 'Disaster Reports' },
    { key: 'projects', label: 'Projects & Programs' },
    { key: 'beneficiaries', label: 'Beneficiaries' },
    { key: 'documents', label: 'Document Management' },
    { key: 'assets', label: 'Equipment & Assets' },
    { key: 'supplies', label: 'Supplies' },
    { key: 'maintenance', label: 'Maintenance' },
    { key: 'events', label: 'Events & Sessions' },
    { key: 'appointments', label: 'Appointments' },
    { key: 'calendar', label: 'Calendar' },
    { key: 'reports', label: 'Reports & Analytics' },
    { key: 'users', label: 'Users' },
    { key: 'roles', label: 'Roles' },
    { key: 'permissions', label: 'Permissions' },
    { key: 'activityLogs', label: 'Activity Logs' },
    { key: 'loginHistory', label: 'Login History' },
    { key: 'settings', label: 'System Settings' },
];

export const PERMISSION_ACTIONS = ['can_view', 'can_add', 'can_edit', 'can_delete', 'can_print', 'can_export', 'can_approve'];
